import = ["~/.config/alacritty/themes/catppuccin-macchiato.toml"]

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = false
opacity = 0.93
title = "Alacritty"

[window.padding]
x = 2
y = 2


[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
